# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1096, 737)
        self.multiplicacion = QtWidgets.QPushButton(Dialog)
        self.multiplicacion.setGeometry(QtCore.QRect(820, 390, 151, 51))
        self.multiplicacion.setObjectName("multiplicacion")
        self.ocho = QtWidgets.QPushButton(Dialog)
        self.ocho.setGeometry(QtCore.QRect(370, 210, 70, 51))
        self.ocho.setObjectName("ocho")
        self.igual = QtWidgets.QPushButton(Dialog)
        self.igual.setGeometry(QtCore.QRect(100, 630, 591, 51))
        self.igual.setObjectName("igual")
        self.uno = QtWidgets.QPushButton(Dialog)
        self.uno.setGeometry(QtCore.QRect(100, 430, 61, 51))
        self.uno.setObjectName("uno")
        self.cuatro = QtWidgets.QPushButton(Dialog)
        self.cuatro.setGeometry(QtCore.QRect(100, 310, 61, 51))
        self.cuatro.setObjectName("cuatro")
        self.nueve = QtWidgets.QPushButton(Dialog)
        self.nueve.setGeometry(QtCore.QRect(620, 210, 61, 51))
        self.nueve.setObjectName("nueve")
        self.dos = QtWidgets.QPushButton(Dialog)
        self.dos.setGeometry(QtCore.QRect(370, 430, 61, 51))
        self.dos.setObjectName("dos")
        self.cinco = QtWidgets.QPushButton(Dialog)
        self.cinco.setGeometry(QtCore.QRect(370, 310, 61, 51))
        self.cinco.setObjectName("cinco")
        self.pantalla = QtWidgets.QLabel(Dialog)
        self.pantalla.setGeometry(QtCore.QRect(130, 40, 751, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pantalla.setFont(font)
        self.pantalla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pantalla.setText("")
        self.pantalla.setAlignment(QtCore.Qt.AlignCenter)
        self.pantalla.setObjectName("pantalla")
        self.tres = QtWidgets.QPushButton(Dialog)
        self.tres.setGeometry(QtCore.QRect(620, 430, 61, 51))
        self.tres.setObjectName("tres")
        self.division = QtWidgets.QPushButton(Dialog)
        self.division.setGeometry(QtCore.QRect(820, 480, 151, 51))
        self.division.setObjectName("division")
        self.seis = QtWidgets.QPushButton(Dialog)
        self.seis.setGeometry(QtCore.QRect(620, 310, 61, 51))
        self.seis.setObjectName("seis")
        self.siete = QtWidgets.QPushButton(Dialog)
        self.siete.setGeometry(QtCore.QRect(100, 210, 61, 51))
        self.siete.setObjectName("siete")
        self.cero = QtWidgets.QPushButton(Dialog)
        self.cero.setGeometry(QtCore.QRect(100, 540, 591, 51))
        self.cero.setObjectName("cero")
        self.resta = QtWidgets.QPushButton(Dialog)
        self.resta.setGeometry(QtCore.QRect(820, 300, 151, 51))
        self.resta.setObjectName("resta")
        self.suma = QtWidgets.QPushButton(Dialog)
        self.suma.setGeometry(QtCore.QRect(820, 210, 151, 51))
        self.suma.setObjectName("suma")
        self.limpiar = QtWidgets.QPushButton(Dialog)
        self.limpiar.setGeometry(QtCore.QRect(820, 550, 151, 51))
        self.limpiar.setObjectName("limpiar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.multiplicacion.setText(_translate("Dialog", "X"))
        self.ocho.setText(_translate("Dialog", "8"))
        self.igual.setText(_translate("Dialog", "="))
        self.uno.setText(_translate("Dialog", "1"))
        self.cuatro.setText(_translate("Dialog", "4"))
        self.nueve.setText(_translate("Dialog", "9"))
        self.dos.setText(_translate("Dialog", "2"))
        self.cinco.setText(_translate("Dialog", "5"))
        self.tres.setText(_translate("Dialog", "3"))
        self.division.setText(_translate("Dialog", "/"))
        self.seis.setText(_translate("Dialog", "6"))
        self.siete.setText(_translate("Dialog", "7"))
        self.cero.setText(_translate("Dialog", "0"))
        self.resta.setText(_translate("Dialog", "-"))
        self.suma.setText(_translate("Dialog", "+"))
        self.limpiar.setText(_translate("Dialog", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
